### PR TITLE
Strategy card design

### LINKED ISSUE #705: Strategy cards redesign
## Summary
We want to update the design of the strategy cards to include additional information and make the displayed data more intuitive for the user.

## Designs:

[All strategy types](https://www.figma.com/file/YpsatcY9jtxJr0SJwlFYNj/Carbon-Screen-Design?type=design&node-id=9440%3A34572&mode=design&t=yKBhFSNnl4YEv3Qd-1)

## Overview

The new strategy cards will showcase a revamped design of a prices section, displaying a market price indicator alongside order prices so users can easily compare their orders with the current market price. New strategy cards will also feature  additional statistics such as the total strategy budget. While the layout of the overview tab will remain unchanged, the flows for strategy creation and alteration will also stay the same.

In this issue, we will address all the changes applied to the strategy cards except for the price section, which will be described in the following issue [strategy card pricing section](https://github.com/bancorprotocol/carbon-app/issues/773)

## What changes
1.  **Gear icon** 
- Gear icon next to the token pair will replace the manage button
- Move all the manage menu options under the gear icon menu as is(the order of the items in the menu and their behavior remain the same)
- Gear icon will be always visible
- On click- show the list of menu options [mockup](https://www.figma.com/file/YpsatcY9jtxJr0SJwlFYNj/Carbon-Screen-Design?type=design&node-id=8960%3A70095&mode=design&t=SNwEQf00WMC2fZ69-1)
- Use the same open/close animations we currently use for a manage menu
- Any click outside of the open menu will close it(same as current manage menu behavior)
- Use the same tooltips when mouse hover over the menu options

2. **Buy&sell budgets**
- Take budget's fiat value outside the token amount tooltip and it below the budget token amount
- Budget token amount tooltip will display only the full token amount [mockup](https://www.figma.com/file/YpsatcY9jtxJr0SJwlFYNj/Carbon-Screen-Design?type=design&node-id=9440%3A34933&mode=design&t=Bg5DmvE4ICnANUjz-1)
- When mouse hover over the buy and sell budgets, show the same tooltips we currently show when hovering over the budgets under the Buy and Sell sections [buy budget mockup](https://www.figma.com/file/YpsatcY9jtxJr0SJwlFYNj/Carbon-Screen-Design?type=design&node-id=9440%3A36802&mode=design&t=yKBhFSNnl4YEv3Qd-1), [sell budget mockup](https://www.figma.com/file/YpsatcY9jtxJr0SJwlFYNj/Carbon-Screen-Design?type=design&node-id=9440%3A36994&mode=design&t=yKBhFSNnl4YEv3Qd-1)
- Move token icons to the left of the  buy/sell budgets token amounts
- In case we do not have a fiat value of the token:
-- Do not show budget's value using the user defined display currency
-- Show tooltip warning icon next to the token's budget [mockup](https://www.figma.com/file/YpsatcY9jtxJr0SJwlFYNj/Carbon-Screen-Design?type=design&node-id=9440%3A36599&mode=design&t=RI35XKglfM6yQOzb-1)
-- On mouse hover over the icon show tooltip with the following text: "There is no {currency} value for this token" [mockup](https://www.figma.com/file/YpsatcY9jtxJr0SJwlFYNj/Carbon-Screen-Design?type=design&node-id=9440%3A36599&mode=design&t=RI35XKglfM6yQOzb-1)
3. **Total budget** 
- Show the combined sell and buy budget of the strategy using the user defined display currency
- Example:
-- Display currency -> USD
-- Buy budget = $10,000, Sell budget= $5,000=> Total budget = $10,000+$5,000= $15,000
- Total budget tooltip text: "Sum of the {currency} value of the token budgets" [mockup](https://www.figma.com/file/YpsatcY9jtxJr0SJwlFYNj/Carbon-Screen-Design?type=design&node-id=8980%3A72377&mode=design&t=1ddQONgdRxDvc2dK-1)
- In case both tokens have no fiat value, do not show total budget's value using the user defined display currency [mockup](https://www.figma.com/file/YpsatcY9jtxJr0SJwlFYNj/Carbon-Screen-Design?type=design&node-id=8967%3A71409&mode=design&t=1ddQONgdRxDvc2dK-1)
- If only 1 token has a fiat value , show this token fiat value under the total budget using the user defined display currency [mockup](https://www.figma.com/file/YpsatcY9jtxJr0SJwlFYNj/Carbon-Screen-Design?type=design&node-id=9440%3A36599&mode=design&t=yKBhFSNnl4YEv3Qd-1)
4. **Limit/range prices**
- When hovering the mouse over the limit and range price tooltip icons under the buy & sell sections, the following tooltips are displayed:
**Buy section**
-- Both limit and range price tooltips- "This is the price at which you are willing to buy {base token symbol}".
**Sell section**
-- Both limit and range price tooltips- "This is the price at which you are willing to sell {base token symbol}". [mockup](https://www.figma.com/file/YpsatcY9jtxJr0SJwlFYNj/Carbon-Screen-Design?type=design&node-id=9440%3A35109&mode=design&t=Xc4Ye9wLGrKiyV3w-1)
- Limit/range token amount tooltip will display the full token amount 
5. **Strategy status**
- In case the strategy status is inactive, move the inactive reason inside the tooltip [mockup](https://www.figma.com/file/YpsatcY9jtxJr0SJwlFYNj/Carbon-Screen-Design?type=design&node-id=9440%3A36222&mode=design&t=Zk6Mjypan8zdh6Cd-1)
-- Paused strategy tooltip text: "The strategy is paused.  Price indicators are reset"
-- No budget strategy tooltip text: "Strategy is out of budget"
-- Paused strategy with no budget tooltip text: "The strategy is paused and is out of budget. Price indicators are reset"
6. **Twitter icon** 
- There is a saperate task for the twitter share button #716 .

## Whats stays as is

1. Tooltips:
- Active status tooltip
- ROI tooltip
- Buy/Sell title tooltips

2.  All the numbers will adhere to the current numbers display format

### PR DESCRIPTION
**Pull request by GrandSchtroumpf**
fix #705
- [x] Redesign the strategy card without the graph
- [x] Update e2e

As I removed the graphs, we need to merge both PRs before merging.

### CODE REVIEW

**Comment by Costa769** [comment]
A few small issue I've noticed in the preview link

1- There is no tooltip showing whole amount when hovering over the budget token amount, see [mockup](https://www.figma.com/file/YpsatcY9jtxJr0SJwlFYNj/Carbon-Screen-Design?type=design&node-id=9440%3A34933&mode=design&t=be87sQxNc0DUrxOt-1)
2- Total budget tooltip- remove the "Learn how ROI is calculated" text
3- We should display “- - -“ below the budgets only if there is no fiat value for the token, not when the budget is 0.
When budget is 0, show 0 value in user selected currency below the budget amount 
4- ROI tooltip- missing space between "." and "Learn how ROI is calculated"

**Comment by Costa769** [comment]
A few issue:

1- On explorer page, If, for example, user searches for ETH-USDC strategy pair and scrolls down the list of strategy cards, from a certain point no tooltips are displayed when hovering over the graph price points. Probably the same happens on the strategies page in case the user have a long list of strategy cards
2- There is an icon in the total budget tooltip that links to the FAQ page, should be removed
3- Both token budgets font size should be 14 instead of 16 
4- Do not show the market price indicator on the graph in case we do not have a fiat value of the token
5- In case the strategy is inactive, dim also the ROI and total budget section of the card the same way we do with the budget section

**Comment by Costa769** [comment]
Apply the same rounding logic to the order prices and marginal price in the tooltip as we apply on prod


Example:
Wallet address: 0xa6f473548cb679d60cebf7c00e9b37816f0b1e17

**Strategy prices on prod**
image



**Same strategy prices on preview link**
image

**Comment by ashachaf** [comment]
- [ ] change opacity
- marginal price range area opacity from 0.25 -> 1
- range area opacity from 0.25 -> 0.5

- [ ] update out of range text
currently, we add "out of range" text when the price is off the grid.
update the text to say "(off-scale)"

- [ ] sort roi 
incorrect sorting
ROI (Descending) is actually sorting ascending (small to large)
ROI (Ascending) is actually sorting descending (large to small)

- [ ] min price in tool tip
currently, it seems that min price is always == marginal price
image

- [ ] limit order padding
increase mouse over area on limit order so it allows a wider space to trigger the tool tip
stroke widgth = 2px
mouse over area = 20px

- [ ] remove the "budget" text
current: Buy ETH Budget
updated: Buy ETH
current: Sell ETH Budget
updated: Sell ETH

- [ ] market price is not centered
image

- [ ] range tool tip 
 replace `*` with a dot `•` and add a space after it (before the word)

**Comment by ashachaf** [comment]
- [ ] learn more text and link update
current:
• Want to know about prices and their meaning?
[Learn More](https://faq.carbondefi.xyz/)
updated:
[Learn More about marginal price](https://faq.carbondefi.xyz/trading-strategies/order-dynamics)

**Review by ashachaf — APPROVED** [review]

**Review by zavelevsky — APPROVED** [review]
code LGTM!

**Review by tiagofilipenunes — APPROVED** [review]
LGTM

**Pull request merged**
