### PR TITLE
[Simulator] Resize graph with the window

### PR DESCRIPTION
**Pull request by GrandSchtroumpf**
Resize the graph horizontally & vertically
Video:
https://github.com/bancorprotocol/carbon-app/assets/8143464/0c0a9751-e8ef-4797-b586-32cba0c87248

### CODE REVIEW

**Comment by ashachaf** [comment]
- [ ] for screen heigh below min height, you cannot scroll to view the bottom of the chart
https://github.com/bancorprotocol/carbon-app/assets/40430285/0e15c0ec-f5f6-4cb8-a494-c9ca1a630628

**Comment by GrandSchtroumpf** [comment]
I've open an issue for that: https://github.com/bancorprotocol/carbon-app/issues/1052

**Review by pingustar — APPROVED** [review]
Code LGTM

**Comment by pingustar** [comment]
I noticed some flickering when toggling between summary and animation tabs.


https://github.com/bancorprotocol/carbon-app/assets/7262066/cfd11351-75ef-476d-a541-e54c64f31b95

**Pull request merged**
