### PR TITLE
[My Strategies] Add update indicator

### LINKED ISSUE #1300: [My Strategies] Updating state
When creating/editing a strategy we arrive on "My Strategies" page and the updates only arrives after some seconds.
In the meantime there is no indication that the state is stale. This has two effects : 
- UX: user has any indication on what's happening which can be stressful, especially if transaction involves large budgets.
- E2E: tests don't know when the state is updated, which leads to flaky tests.

Solution : 
Display a fetching indication at the top of the strategy list.
- Since the query is on all strategies of the user, we don't know which strategy is loading, so we need a global loading indication.
- Ideally this should not create a layout shifting, so we need to keep the space available all the time.
- This should happen only on fetching a new state, and **not on initial load**.

It could look like this : 

https://github.com/bancorprotocol/carbon-app/assets/8143464/49f75ef0-51e7-47d7-b1bd-dfc963d166ee

### PR DESCRIPTION
**Pull request by GrandSchtroumpf**
fix #1300 

Add an indication that the state is updating in My Strategies page.
This happens only for update, not for the initial loading.

https://github.com/bancorprotocol/carbon-app/assets/8143464/e76bf925-99a2-4fe0-86a9-d91eac0e959c

### CODE REVIEW

**Review by tiagofilipenunes — APPROVED** [review]
LGTM, hope this improves e2e test stability

**Comment by Costa769** [comment]
- [ ] On the Ethereum app, the indicator is not displayed; despite making several deposits and withdrawals, the indicator does not appear.
- [ ] On the SEI app, the indicator is visible for only half a second. Perhaps we can extend its appearance by 1-2 seconds.

**Review by tiagofilipenunes — APPROVED** [review]
LGTM

**Comment by tiagofilipenunes** [comment]
fix #485 cc @Costa769

**Comment by GrandSchtroumpf** [comment]
@tiagofilipenunes it doesn't actually fix the issue since the indicator is now totally transparent. At this point, it's only for E2E.

**Pull request merged**
